### ISSUE TITLE
error encountered when running train.py 

### ISSUE THREAD

**Issue by lindsey98** [msn199959/Logo-2k-plus-Dataset#7]
I get the following error when running train.py when I specify to use resnet: 
Traceback (most recent call last):
  File "train.py", line 56, in <module>
    net = model.attention_net(topN=PROPOSAL_NUM)
  File "/home/l/liny/Logo-2k-plus-Dataset/Drna-master/core/model_resnet.py", line 75, in __init__
    self.aug_net = aug_net()
  File "/home/l/liny/Logo-2k-plus-Dataset/Drna-master/core/model_resnet.py", line 39, in __init__
    self.features = net.get_features()
AttributeError: 'NoneType' object has no attribute 'get_features'

**Comment by cristianvasquez** [comment]
the same happens with model_vgg

**Comment by youliangalex** [comment]
FYI: https://github.com/msn199959/Logo-2k-plus-Dataset/issues/10#issue-640520505

**Comment by Mingruizeng** [comment]
I get the following error when running train.py,(I change train_iamges_root.txt to train.txt in theDrna-master, the same as test.txt)
Traceback(most recent call last):
Traceback (most recent call last):
  File "F:/ZMR/Logo-2k-plus-Dataset-master/Drna-master/train.py", line 56, in <module>
    net = model.attention_net(topN=PROPOSAL_NUM)
  File "F:\ZMR\Logo-2k-plus-Dataset-master\Drna-master\core\model_resnet.py", line 75, in __init__
    self.aug_net = aug_net()
TypeError: __init__() missing 1 required positional argument: 'NUM_CLASSES'

**Comment by jruizc03** [comment]
Did someone encountered how to resolve the error raised? I am also stucked at this point.

**Comment by pranaysawant** [comment]
Any Update here? I am facing same issue. or @msn199959 could provide pretrained models?

**Comment by madsemilmj** [comment]
Any updates on this issue, someone managed to resolve it?
